### ISSUE TITLE
APK for latest version missing in releases

### ISSUE THREAD

**Issue by IzzySoft** [VenomVendor/DeduplicateSMS#12]
Could you please add the APK for the lastest version to its corresponding tag – for those outside from Playstore? Thanks!

**Comment by IzzySoft** [comment]
@VenomVendor could you please add the APK ^^?

**Comment by VenomVendor** [comment]
@IzzySoft You can find it here in [releases](https://github.com/VenomVendor/DeduplicateSMS/releases).

**Comment by IzzySoft** [comment]
@VenomVendor not for the latest version (2.1.0) – only for 2.0.0 from 7/2017.

**Comment by VenomVendor** [comment]
Thanks for pointing out, I've updated now.

**Comment by IzzySoft** [comment]
Thanks for updating!
