### ISSUE TITLE
App Struck at 0/0

### ISSUE THREAD

**Issue by VenomVendor** [VenomVendor/DeduplicateSMS#5]
<a href="https://play.google.com/store/apps/details?id=com.venomvendor.sms.deduplicate&reviewId=Z3A6QU9xcFRPRWlNcE1tM0J5VnpzYjNiQVowM2F1dG81MGpPWGlieHVXdWtBbEtpQlhkQ3c0b0lfWWQ3SHZSeDdScFROaGNsVXByd1BDdF9MWGI0aU0xZDJr"><img width="593" alt="App Struck at 0/0" src="https://cloud.githubusercontent.com/assets/1086927/16418590/2b9686ca-3d68-11e6-9d5f-4d54b4aac18d.png"></a>

**Comment by axeker11** [comment]
issue

**Comment by Ericson2314** [comment]
I'm getting the same thing on my new Pixel. I got ~40,000 duplicates from a lousy non-idempotent backup app. 

I'm taking a wild guess this is an asymptomatic performance problem, and the 0 numerator isn't getting updated because it's blocked on some sort of database IO.

**Comment by VenomVendor** [comment]
@Ericson2314 can you share build version of Pixel, I will test the same in my device.

**Comment by Ericson2314** [comment]
Sorry, which number is that exactly? My OS version is `7.1.1`.

**Comment by VenomVendor** [comment]
> Settings > About phone > Build number

**Comment by Ericson2314** [comment]
Ah ok, `NOF27B`. Thanks!

**Comment by VenomVendor** [comment]
@Ericson2314 Tested in my device having same build number, no luck.
Will you be able to help me, it should take less than 30mins over (Skype + TeamViewer)

**Comment by Ericson2314** [comment]
Oh, sorry I rudely never responded! (Don't have Skype.) Thanks for fixing!
